In [4]:
import numpy as np
np.random.seed(0)
x = np.random.randint(5, size = (4,4))
x

array([[4, 0, 3, 3],
       [3, 1, 3, 2],
       [4, 0, 0, 4],
       [2, 1, 0, 1]])

In [10]:
x[2, 1] = 100
x

array([[  4,   0,   3,   3],
       [  3,   1,   3,   2],
       [  4, 100,   0,   4],
       [  2,   1,   0,   1]])

In [28]:
x[1, 3] = 200
x

array([[  4,   0,   3,   3],
       [  3,   1,   3, 200],
       [  4, 100,   0,   4],
       [  2,   1,   0,   1]])

In [32]:
x3_copy = x[2, :].copy()
x3_copy

array([  4, 100,   0,   4])

In [34]:
x3_copy.reshape((4,1))

array([[  4],
       [100],
       [  0],
       [  4]])