In [5]:
import numpy as np
from numpy import random
rand = random.RandomState(6)
j = rand.randint(100, size = 20)
j

array([10, 73, 99, 84, 79, 80, 62, 25,  1, 75, 77, 57, 26, 33, 68, 33,  8,
        2, 76, 84])

In [19]:
ind = np.array([3, 11])
j[ind]

array([84, 57])

In [21]:
ind = np.array([2, 16, 8])
j[ind]

array([99,  8,  1])

In [17]:
ind = np.array([[9, 2], [18, 7]])
j[ind]

array([[75, 99],
       [76, 25]])